# Generated by Django 6.0.2 on 2026-06-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_experiencia_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_navegacion',
            field=models.CharField(choices=[('desplegable', 'Desplegable'), ('fijo', 'Fijo')], default='desplegable', max_length=15, verbose_name='Tipo de Navegación'),
        ),
    ]
