# Generated by Django 6.0.2 on 2026-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_tipo_navegacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='formacion_educativa',
            field=models.CharField(blank=True, db_column='Formacion_Educativa', default='', max_length=35, verbose_name='Formación Educativa'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Nombre', default='', max_length=35, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_numero',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Numero', default='', max_length=14, verbose_name='Número Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, db_column='Contacto_Emergencia_Parentesco', default='', max_length=15, verbose_name='Parentesco Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='eps',
            field=models.CharField(blank=True, choices=[('Nueva EPS', 'Nueva EPS'), ('Sanitas', 'Sanitas'), ('SURA', 'SURA'), ('Salud Total', 'Salud Total'), ('Compensar', 'Compensar'), ('Famisanar', 'Famisanar'), ('Coosalud', 'Coosalud'), ('Mutual Ser', 'Mutual Ser'), ('SOS', 'SOS'), ('Salud Mía', 'Salud Mía'), ('Aliansalud', 'Aliansalud'), ('Dusakawi', 'Dusakawi'), ('Salud Bolívar', 'Salud Bolívar'), ('Savia Salud', 'Savia Salud'), ('Cajacopi', 'Cajacopi'), ('Asmet Salud', 'Asmet Salud'), ('Emssanar', 'Emssanar'), ('Capital Salud', 'Capital Salud')], db_column='EPS', default='', max_length=20, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo')], db_column='tipo_contrato', default='', max_length=10, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='cajero',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='Turno', default='', max_length=7, verbose_name='Turno'),
        ),
    ]
