# Generated by Django 6.0.2 on 2026-05-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='experiencia_laboral',
            field=models.FileField(blank=True, null=True, upload_to='experiencia_laboral/', verbose_name='Experiencia Laboral (PDF)'),
        ),
    ]
