# Generated by Django 6.0.2 on 2026-05-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('PSE', 'PSE')], max_length=16, verbose_name='Método de Pago'),
        ),
    ]
