# Generated by Django 6.0.2 on 2026-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproducto',
            name='notas',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Notas/Modificaciones'),
        ),
    ]
