# Generated by Django 6.0.2 on 2026-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0013_alter_detalleproductomateriap_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductomateriap',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Unidad Usada'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
