# Generated by Django 6.0.2 on 2026-06-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0014_alter_detalleproductomateriap_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiaprima',
            unique_together={('nombre_materia_prima', 'cantidad_por_unidad')},
        ),
    ]
