# Generated by Django 6.0.2 on 2026-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0015_alter_materiaprima_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductomateriap',
            name='es_prioridad',
            field=models.BooleanField(default=False, verbose_name='Es Prioridad'),
        ),
    ]
