# Generated by Django 6.0.2 on 2026-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Hamburguesas', 'Hamburguesas'), ('Perros Calientes', 'Perros Calientes'), ('Entradas y Snacks', 'Entradas y Snacks'), ('Combos', 'Combos'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres'), ('Adiciones', 'Adiciones'), ('Salsas', 'Salsas')], default='', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Descripción'),
        ),
    ]
