# Generated by Django 6.0.2 on 2026-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Descripción'),
        ),
    ]
