# Generated by Django 6.0.2 on 2026-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, default='', max_length=35, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Teléfono'),
        ),
    ]
