# Generated by Django 6.0.2 on 2026-06-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='Correo Electrónico'),
        ),
    ]
